services:
  docs:
    image: order_service_local_docs
    container_name: order_service_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./order_service:/app/order_service:z
    ports:
      - '9000:9000'
    command: /start-docs
