# Generated by Django 5.1.9 on 2025-08-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birth_date_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
