CREATE TABLE address
(
    id_address   BIGINT       NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    created_user VARCHAR(255) NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_user VARCHAR(255) NOT NULL,
    street       VARCHAR(200) NOT NULL,
    city         VARCHAR(100) NOT NULL,
    state        VARCHAR(50)  NOT NULL,
    zip_code     VARCHAR(8)   NOT NULL,
    neighborhood VARCHAR(50)  NOT NULL,
    number       INTEGER,
    CONSTRAINT pk_address PRIMARY KEY (id_address)
);

CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    company_id BIGINT,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE company
(
    company_id     BIGINT       NOT NULL,
    cnpj           VARCHAR(14)  NOT NULL,
    bussiness_name VARCHAR(100) NOT NULL,
    image_url      VARCHAR(255),
    CONSTRAINT pk_company PRIMARY KEY (company_id)
);

CREATE TABLE customer
(
    customer_id   BIGINT      NOT NULL,
    cpf           VARCHAR(11) NOT NULL,
    date_of_birth TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    image_url     VARCHAR(11) NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

CREATE TABLE delivery_person
(
    delivery_person_id BIGINT NOT NULL,
    cpf                VARCHAR(255),
    vehicle_type       VARCHAR(255),
    image_url          VARCHAR(255),
    active             BOOLEAN,
    CONSTRAINT pk_deliveryperson PRIMARY KEY (delivery_person_id)
);

CREATE TABLE "order"
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    created_user     VARCHAR(255)                            NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_user     VARCHAR(255)                            NOT NULL,
    company_id  BIGINT,
    customer_id BIGINT,
    order_date       TIMESTAMP WITHOUT TIME ZONE,
    order_amount     DECIMAL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id           BIGINT,
    product_id_product BIGINT,
    quantity           DOUBLE PRECISION,
    price              DECIMAL,
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

CREATE TABLE order_log
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT,
    text     VARCHAR(255),
    log_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orderlog PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT,
    payment_method VARCHAR(255),
    amount         DECIMAL,
    payment_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE product
(
    id_product      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    created_user    VARCHAR(255)                            NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_user    VARCHAR(255)                            NOT NULL,
    company_id BIGINT,
    name            VARCHAR(255),
    description     VARCHAR(255),
    price           DECIMAL,
    quantity        INTEGER,
    image_url       VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id_product)
);

CREATE TABLE product_log
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action             VARCHAR(255),
    product_id_product BIGINT                                  NOT NULL,
    log_date           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_productlog PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    user_id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    created_user    VARCHAR(255) NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_user    VARCHAR(255),
    username        VARCHAR(50)  NOT NULL,
    email           VARCHAR(50)  NOT NULL,
    phone           VARCHAR(50),
    role            VARCHAR(255),
    expo_push_token VARCHAR(50),
    keycloak_user_id UUID NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE user_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_user_id BIGINT,
    action       VARCHAR(255),
    log_date     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_userlog PRIMARY KEY (id)
);

ALTER TABLE company
    ADD CONSTRAINT uc_company_cnpj UNIQUE (cnpj);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (company_id);

ALTER TABLE company
    ADD CONSTRAINT FK_COMPANY_ON_COMPANYID FOREIGN KEY (company_id) REFERENCES "user" (user_id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CUSTOMERID FOREIGN KEY (customer_id) REFERENCES "user" (user_id);

ALTER TABLE delivery_person
    ADD CONSTRAINT FK_DELIVERYPERSON_ON_DELIVERYPERSONID FOREIGN KEY (delivery_person_id) REFERENCES "user" (user_id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_PRODUCT_ID_PRODUCT FOREIGN KEY (product_id_product) REFERENCES product (id_product);

ALTER TABLE order_log
    ADD CONSTRAINT FK_ORDERLOG_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_COMPANY_USERID FOREIGN KEY (company_id) REFERENCES company (company_id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_CUSTOMER_USERID FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE product_log
    ADD CONSTRAINT FK_PRODUCTLOG_ON_PRODUCT_ID_PRODUCT FOREIGN KEY (product_id_product) REFERENCES product (id_product);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_COMPANY_USERID FOREIGN KEY (company_id) REFERENCES company (company_id);

ALTER TABLE user_log
    ADD CONSTRAINT FK_USERLOG_ON_USER_USERID FOREIGN KEY (user_user_id) REFERENCES "user" (user_id);