ALTER TABLE customer
ADD CONSTRAINT fk_customer_user
FOREIGN KEY (customer_id)
REFERENCES "user"(user_id);

ALTER TABLE delivery_person
ADD CONSTRAINT fk_delivery_person_user
FOREIGN KEY (delivery_person_id)
REFERENCES "user"(user_id);

ALTER TABLE address
ALTER COLUMN id_address
ADD GENERATED BY DEFAULT AS IDENTITY;