# Generated by Django 5.1.9 on 2025-07-14 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(default='Admin', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(default='Admin', max_length=100)),
                ('availability', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(default='Admin', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(default='Admin', max_length=100)),
                ('full_name', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.IntegerField(choices=[(1, 'Administrator'), (2, 'Customer'), (3, 'Delivery Man')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(default='Admin', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(default='Admin', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(default='Admin', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(default='Admin', max_length=100)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('app_origin', models.CharField(max_length=100)),
                ('order_status', models.IntegerField(choices=[(1, 'Aguardando Coleta'), (2, 'Em Rota'), (3, 'Entregue'), (4, 'Cancelado'), (5, 'Em Produção')])),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliveryperson')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplementaryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_street', models.CharField(max_length=100)),
                ('delivery_neighborhood', models.CharField(blank=True, max_length=100)),
                ('delivery_number', models.CharField(max_length=10)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_country', models.CharField(max_length=100)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complementary_order', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.CharField(max_length=50)),
                ('start_longitude', models.CharField(max_length=50)),
                ('end_latitude', models.CharField(max_length=50)),
                ('end_longitude', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_order', to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('origin_ip', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(default='Admin', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(default='Admin', max_length=100)),
                ('message', models.TextField()),
                ('delivery_channel', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
