# Generated by Django 5.1.9 on 2025-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryorder',
            name='full_delivery_address',
            field=models.CharField(editable=False, max_length=400),
        ),
        migrations.AlterField(
            model_name='complementaryorder',
            name='full_pickup_address',
            field=models.CharField(editable=False, max_length=400),
        ),
    ]
