# Generated by Django 5.1.9 on 2025-05-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_complementaryorder_full_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementaryorder',
            name='full_delivery_address',
        ),
        migrations.RemoveField(
            model_name='complementaryorder',
            name='full_pickup_address',
        ),
        migrations.AlterField(
            model_name='complementaryorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complementary_order', to='core.order'),
        ),
    ]
