# Generated by Django 5.1.9 on 2025-07-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_user_order_email_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(max_length=200),
        ),
    ]
