# Generated by Django 5.1.9 on 2025-05-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_complementaryorder_full_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='event_status',
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_order', to='core.order'),
        ),
    ]
