# Generated by Django 5.1.9 on 2025-07-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='msg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(verbose_name=10),
        ),
    ]
