# Generated by Django 5.1.9 on 2025-07-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderlog_msg_alter_orderlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='msg',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
