# Generated by Django 5.1.9 on 2025-07-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_orderlog_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='msg',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
