# Generated by Django 5.1.9 on 2025-08-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userlog_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
