# Generated by Django 5.1.9 on 2025-07-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_delivery_person_alter_accesslog_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='password',
        ),
    ]
