# Generated by Django 5.1.9 on 2025-07-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_establishment_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
