# Generated by Django 5.1.9 on 2025-07-30 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_establishment_phone_alter_establishment_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='administrator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
