# Generated by Django 5.1.9 on 2025-08-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_url'),
        ('core', '0011_establishment_administrator'),
    ]

    operations = [
    ]
